const API='http://127.0.0.1:5000';let token=null;let currentProcess=null;let currentFindings=[];

// V1.0 - autenticação local e experiência operacional consolidada
let authMode='login';
async function authStatus(){
  try{const r=await fetch(`${API}/api/auth/status`);const d=await r.json();
    if(d.authenticated){authGate.classList.add('hidden');currentUser.textContent=d.user.nome;logoutBtn.classList.remove('hidden');return true;}
    authGate.classList.remove('hidden');logoutBtn.classList.add('hidden');authMode=d.configured?'login':'setup';setupNameWrap.classList.toggle('hidden',authMode!=='setup');authTitle.textContent=authMode==='setup'?'Configuração inicial':'Entrar no Hub';authText.textContent=authMode==='setup'?'Crie o primeiro operador local. A senha é armazenada como hash no SQLite.':'Informe suas credenciais para acessar a operação.';authSubmit.textContent=authMode==='setup'?'Criar operador e entrar':'Entrar';return false;
  }catch{authMessage.textContent='Não foi possível conectar ao servidor local.';return false;}
}
authSubmit.onclick=async()=>{authMessage.textContent='';const payload={username:authUser.value,password:authPassword.value,nome:setupName.value};const endpoint=authMode==='setup'?'/api/auth/setup':'/api/auth/login';try{const r=await fetch(`${API}${endpoint}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw Error(d.error);authPassword.value='';await authStatus();await refreshProtected();}catch(e){authMessage.textContent=e.message;}};
authPassword.addEventListener('keydown',e=>{if(e.key==='Enter')authSubmit.click();});
logoutBtn.onclick=async()=>{await fetch(`${API}/api/auth/logout`,{method:'POST'});currentUser.textContent='Acesso protegido';await authStatus();};
async function refreshProtected(){dashboard();loadHistory();loadRules();loadLogs();}
const modules=[{icon:'📊',name:'Spreadsheet Automation',status:'FUNCIONAL V1.0',desc:'Analisa com regras operacionais configuráveis e mantém histórico auditável no SQLite.',tags:['Python','Pandas','OpenPyXL','SQLite']},{icon:'📁',name:'File Organizer',status:'PLANEJADO',desc:'Classifica documentos e organiza arquivos por regras operacionais.',tags:['Python','Filesystem','XML']},{icon:'📧',name:'Daily Report',status:'PLANEJADO',desc:'Consolida mensagens e pendências em relatório operacional.',tags:['Python','Microsoft Graph','API']}];
moduleGrid.innerHTML=modules.map(m=>`<article class="card"><span class="badge">${m.status}</span><div class="icon">${m.icon}</div><h4>${m.name}</h4><p>${m.desc}</p><div class="tags">${m.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div></article>`).join('');
const esc=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]));
const fmtDate=v=>v?new Date(v).toLocaleString('pt-BR'):'—';
function msg(t,e=false){message.textContent=t;message.className='message'+(e?' error':'')}
async function health(){try{let r=await fetch(`${API}/api/health`);if(!r.ok)throw 0;let d=await r.json();apiStatus.textContent='ONLINE';apiDetail.textContent=`Flask + SQLite · v${d.version}`;}catch{apiStatus.textContent='OFFLINE';apiDetail.textContent='Execute: python python/app.py';}}
async function dashboard(){try{let d=await (await fetch(`${API}/api/dashboard`)).json();dbFiles.textContent=d.files;dbRecords.textContent=d.records;dbOccurrences.textContent=d.occurrences;dbDecisions.textContent=d.decisions;dbKeep.textContent=d.keep;dbRemove.textContent=d.remove;dbReview.textContent=d.review;}catch{}}
async function loadHistory(){try{let r=await fetch(`${API}/api/history`);let d=await r.json();historyBody.innerHTML=d.history.length?d.history.map(x=>`<tr><td><strong>${esc(x.process_code)}</strong></td><td>${esc(x.arquivo)}</td><td>${fmtDate(x.data)}</td><td>${x.registros}</td><td>${x.ocorrencias}</td><td>${x.manter||0}</td><td>${x.remover||0}</td><td>${x.revisar||0}</td><td>${esc(x.status)}</td><td><button class="mini history-open" data-code="${esc(x.process_code)}">Abrir</button></td></tr>`).join(''):'<tr><td colspan="10">Nenhum processamento registrado.</td></tr>';document.querySelectorAll('.history-open').forEach(b=>b.onclick=()=>openHistory(b.dataset.code));}catch{historyBody.innerHTML='<tr><td colspan="10">Não foi possível carregar o histórico.</td></tr>';}}
async function openHistory(code){try{let r=await fetch(`${API}/api/history/${encodeURIComponent(code)}`);let d=await r.json();if(!r.ok)throw Error(d.error);historyDetail.classList.remove('hidden');historyDetailTitle.textContent=`${d.process.process_code} · ${d.process.arquivo}`;historyMeta.innerHTML=`<span><small>Iniciado</small><strong>${fmtDate(d.process.data)}</strong></span><span><small>Finalizado</small><strong>${fmtDate(d.process.finalizado_em)}</strong></span><span><small>Registros</small><strong>${d.process.registros}</strong></span><span><small>Ocorrências</small><strong>${d.process.ocorrencias}</strong></span>`;historyDetailBody.innerHTML=d.decisions.length?d.decisions.map(x=>`<tr><td><strong>${esc(x.hub_id)}</strong></td><td>${esc(x.finding_id)}</td><td>${x.linha??'—'}</td><td>${x.linha_final??'—'}</td><td>${esc(x.tipo)}</td><td>${esc(x.severidade||'—')}</td><td>${esc(x.decisao)}</td><td>${fmtDate(x.data)}</td></tr>`).join(''):'<tr><td colspan="8">Nenhuma decisão registrada.</td></tr>';historyDetail.scrollIntoView({behavior:'smooth',block:'start'});}catch(e){msg(e.message,true)}}
closeHistory.onclick=()=>historyDetail.classList.add('hidden');
health();authStatus().then(ok=>{if(ok)refreshProtected();});
async function loadRules(){try{let r=await fetch(`${API}/api/rules`);let d=await r.json();ruleExact.checked=d.exact_duplicate?.enabled!==false;ruleOperational.checked=d.operational_duplicate?.enabled!==false;ruleRequired.checked=d.required_fields?.enabled!==false;ruleDate.checked=d.datetime_order?.enabled!==false;ruleCompleted.checked=d.completed_without_exit?.enabled!==false;ruleStatus.checked=d.allowed_status?.enabled===true;operationalFields.value=(d.operational_duplicate?.fields||[]).join(', ');requiredFields.value=(d.required_fields?.fields||[]).join(', ');allowedStatuses.value=(d.allowed_status?.values||[]).join(', ');rulesInfo.textContent='Configuração carregada.';}catch{rulesInfo.textContent='Não foi possível carregar as regras.';}}
const splitList=v=>v.split(',').map(x=>x.trim()).filter(Boolean);
saveRules.onclick=async()=>{let current=await (await fetch(`${API}/api/rules`)).json();current.exact_duplicate={...(current.exact_duplicate||{}),enabled:ruleExact.checked};current.operational_duplicate={...(current.operational_duplicate||{}),enabled:ruleOperational.checked,fields:splitList(operationalFields.value)};current.required_fields={...(current.required_fields||{}),enabled:ruleRequired.checked,fields:splitList(requiredFields.value)};current.datetime_order={...(current.datetime_order||{}),enabled:ruleDate.checked};current.completed_without_exit={...(current.completed_without_exit||{}),enabled:ruleCompleted.checked};current.allowed_status={...(current.allowed_status||{}),enabled:ruleStatus.checked,values:splitList(allowedStatuses.value)};let r=await fetch(`${API}/api/rules`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(current)});if(r.ok){rulesInfo.textContent='Regras salvas. Próximas análises usarão esta configuração.';msg('Regras operacionais atualizadas.');}else rulesInfo.textContent='Erro ao salvar regras.';}


analyzeBtn.onclick=async()=>{let f=fileInput.files[0];if(!f)return msg('Selecione um arquivo Excel primeiro.',true);analyzeBtn.disabled=true;msg('Analisando planilha...');let fd=new FormData();fd.append('file',f);try{let r=await fetch(`${API}/api/spreadsheet/analyze`,{method:'POST',body:fd});let d=await r.json();if(!r.ok)throw Error(d.error);token=d.token;currentProcess=d.process_code;render(d);msg(`Análise concluída · ${d.process_code}. Revise as ocorrências e registre suas decisões.`);dashboard();loadHistory();}catch(e){msg(e.message,true)}finally{analyzeBtn.disabled=false}};
function render(d){results.classList.remove('hidden');downloadBtn.classList.add('hidden');rowsMetric.textContent=d.summary.rows;cleanMetric.textContent=d.summary.clean_records;criticalMetric.textContent=d.summary.critical;warningMetric.textContent=d.summary.warning;fileMeta.innerHTML=`<p><strong>${esc(d.filename)}</strong></p><p><strong>${esc(d.process_code)}</strong></p><p>Aba: ${esc(d.sheet)}</p><p>${d.summary.columns} colunas · ${d.summary.rows} registros</p>`;issues.innerHTML=d.issues.map(x=>`<div class="issue">${esc(x)}</div>`).join('');currentFindings=d.findings||[];findingsBody.innerHTML=currentFindings.length?currentFindings.map(f=>`<tr data-finding-id="${esc(f.id)}" data-hub="${esc(f.hub_id)}" data-line="${f.excel_row}" data-type="${esc(f.type)}" data-severity="${esc(f.severity)}" data-message="${esc(f.message)}"><td><strong>${esc(f.hub_id)}</strong><br><small>${f.id}</small></td><td>${f.excel_row}</td><td>${esc(f.type)}</td><td>${esc(f.severity)}</td><td>${esc(f.message)}</td><td><select class="decision" data-id="${f.id}" data-state="${esc(f.decision)}"><option ${f.decision==='Revisar'?'selected':''}>Revisar</option><option ${f.decision==='Manter'?'selected':''}>Manter</option><option ${f.decision==='Remover'?'selected':''}>Remover</option></select></td><td>${f.related_row?`<button class="mini compare" data-id="${f.id}">Comparar</button>`:'—'}</td></tr>`).join(''):'<tr><td colspan="7">Nenhuma ocorrência.</td></tr>';setupReviewUX();previewHead.innerHTML='<tr>'+d.preview.columns.map(c=>`<th>${esc(c)}</th>`).join('')+'</tr>';previewBody.innerHTML=d.preview.rows.map(r=>'<tr>'+d.preview.columns.map(c=>`<td>${esc(r[c])}</td>`).join('')+'</tr>').join('');}
async function saveDecision(id,decision){try{let r=await fetch(`${API}/api/spreadsheet/decision`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,finding_id:id,decision})});let d=await r.json();if(!r.ok)throw Error(d.error);msg(`${d.process_code} · ${d.hub_id}: decisão ${decision} registrada.`);dashboard();loadHistory();}catch(e){msg(e.message,true)}}
async function compare(id){try{let r=await fetch(`${API}/api/spreadsheet/${token}/finding/${id}`);let d=await r.json();if(!r.ok)throw Error(d.error);comparePanel.classList.remove('hidden');compareTitle.textContent=`${currentProcess} · ${d.finding.hub_id} · linha original ${d.finding.excel_row} x linha ${d.finding.related_row}`;compareReason.textContent=d.finding.message;compareBody.innerHTML=d.fields.map(x=>`<tr><td><strong>${esc(x.field)}</strong></td><td>${esc(x.related)}</td><td>${esc(x.current)}</td></tr>`).join('');comparePanel.scrollIntoView({behavior:'smooth',block:'center'});}catch(e){msg(e.message,true)}}
closeCompare.onclick=()=>comparePanel.classList.add('hidden');
processBtn.onclick=async()=>{if(!token)return msg('Analise um arquivo primeiro.',true);const pending=[...document.querySelectorAll('.decision')].filter(x=>x.value==='Revisar').length;if(pending&&!confirm(`${pending} ocorrência(s) ainda estão como Revisar. Elas serão mantidas na planilha e registradas para auditoria. Deseja gerar o arquivo mesmo assim?`))return;processBtn.disabled=true;msg('Aplicando decisões e gerando planilha...');try{let r=await fetch(`${API}/api/spreadsheet/process`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});let d=await r.json();if(!r.ok)throw Error(d.error);downloadBtn.href=`${API}${d.download_url}`;downloadBtn.textContent=`Baixar ${d.output_filename}`;downloadBtn.classList.remove('hidden');msg(`${d.process_code} concluído. ${d.removed} registro(s) removido(s). Histórico salvo no SQLite.`);dashboard();loadHistory();loadLogs();}catch(e){msg(e.message,true)}finally{processBtn.disabled=false}};
async function loadLogs(){try{let d=await (await fetch(`${API}/api/logs`)).json();activityLog.innerHTML=d.logs.length?d.logs.map(l=>`<div class="log"><span>${l.time}</span><strong>${esc(l.action)}</strong><span>${esc(l.status)}</span></div>`).join(''):'<div class="log"><span>--:--</span><strong>Aguardando execução</strong><span>—</span></div>';}catch{}}


// V0.8 - filtros, busca, contadores e ações seguras em lote
function setupReviewUX(){
  const types=[...new Set(currentFindings.map(f=>f.type).filter(Boolean))].sort();
  typeFilter.innerHTML='<option value="">Todos os tipos</option>'+types.map(t=>`<option>${esc(t)}</option>`).join('');
  reviewSearch.value=''; severityFilter.value=''; typeFilter.value=''; decisionFilter.value='';
  document.querySelectorAll('.decision').forEach(x=>{x.dataset.state=x.value;x.onchange=async()=>{x.dataset.state=x.value;await saveDecision(x.dataset.id,x.value);applyReviewFilters();};});
  document.querySelectorAll('.compare').forEach(x=>x.onclick=()=>compare(x.dataset.id));
  [reviewSearch,severityFilter,typeFilter,decisionFilter].forEach(el=>{el.oninput=applyReviewFilters;el.onchange=applyReviewFilters;});
  clearFilters.onclick=()=>{reviewSearch.value='';severityFilter.value='';typeFilter.value='';decisionFilter.value='';applyReviewFilters();};
  bulkReview.onclick=()=>bulkDecision('Revisar'); bulkKeep.onclick=()=>bulkDecision('Manter');
  applyReviewFilters();
}
function visibleReviewRows(){return [...findingsBody.querySelectorAll('tr[data-finding-id]')].filter(r=>!r.classList.contains('review-row-hidden'));}
function applyReviewFilters(){
  const q=(reviewSearch?.value||'').trim().toLowerCase(), sev=severityFilter?.value||'', typ=typeFilter?.value||'', dec=decisionFilter?.value||'';
  const rows=[...findingsBody.querySelectorAll('tr[data-finding-id]')];
  rows.forEach(r=>{const sel=r.querySelector('.decision');const hay=[r.dataset.hub,r.dataset.line,r.dataset.type,r.dataset.severity,r.dataset.message].join(' ').toLowerCase();const ok=(!q||hay.includes(q))&&(!sev||r.dataset.severity===sev)&&(!typ||r.dataset.type===typ)&&(!dec||sel?.value===dec);r.classList.toggle('review-row-hidden',!ok);});
  const vis=visibleReviewRows(); reviewCounter.textContent=`${vis.length} de ${rows.length} ocorrência(s) exibida(s)`;
  const pending=rows.filter(r=>r.querySelector('.decision')?.value==='Revisar').length; pendingCounter.textContent=`${pending} para revisar`; if(typeof processGuard!=='undefined'&&processGuard) processGuard.textContent=pending?`${pending} ocorrência(s) continuam em Revisar. Elas serão preservadas e registradas no histórico.`:'Todas as ocorrências possuem uma decisão. O processamento está pronto para finalizar.';
}
async function bulkDecision(decision){
  const rows=visibleReviewRows(); if(!rows.length)return msg('Nenhuma ocorrência visível para aplicar a ação.',true);
  const targets=rows.map(r=>r.querySelector('.decision')).filter(s=>s&&s.value!==decision);
  if(!targets.length)return msg(`Todos os itens filtrados já estão como ${decision}.`);
  for(const s of targets){s.value=decision;s.dataset.state=decision;await saveDecision(s.dataset.id,decision);}
  applyReviewFilters(); msg(`${targets.length} ocorrência(s) filtrada(s) marcadas como ${decision}.`);
}
